///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestJunitReport
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestJunitReportRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cde03a6b-3305-48bf-b8c7-138d2f8f344e")]
    public partial class TestJunitReportRepository : RepoGenBaseFolder
    {
        static TestJunitReportRepository instance = new TestJunitReportRepository();
        TestJunitReportRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the TestJunitReportRepository element repository.
        /// </summary>
        [RepositoryFolder("cde03a6b-3305-48bf-b8c7-138d2f8f344e")]
        public static TestJunitReportRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestJunitReportRepository() 
            : base("TestJunitReportRepository", "/", null, 0, false, "cde03a6b-3305-48bf-b8c7-138d2f8f344e", ".\\RepositoryImages\\TestJunitReportRepositorycde03a6b.rximgres")
        {
            _applicationundertest = new TestJunitReportRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cde03a6b-3305-48bf-b8c7-138d2f8f344e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b37baff4-ff5f-4f37-b0cc-131c03507304")]
        public virtual TestJunitReportRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestJunitReportRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b37baff4-ff5f-4f37-b0cc-131c03507304")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productsInfo;
            RepoItemInfo _solutionsInfo;
            RepoItemInfo _ranorexInfo;
            RepoItemInfo _resourcesInfo;
            RepoItemInfo _supportInfo;
            RepoItemInfo _functionaluitestautomationwithintelInfo;
            RepoItemInfo _ranorexgaugeb2Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "b37baff4-ff5f-4f37-b0cc-131c03507304", "")
            {
                _productsInfo = new RepoItemInfo(this, "Products", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", 30000, null, "03c85a99-f0b2-4a45-b6c0-db9051ec0f04");
                _solutionsInfo = new RepoItemInfo(this, "Solutions", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Solutions']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Solutions']", 30000, null, "4174daf7-39bf-4b4d-bce4-d4b3cfd90d78");
                _ranorexInfo = new RepoItemInfo(this, "Ranorex", ".//div[#'et-boc']/header/div/div[2]//a[@href='https://www.ranorex.com/']/?/?/img[@title='Ranorex-Logo-WithTagline']", ".//div[#'et-boc']//img", 30000, null, "911735bc-fea3-4a07-90f6-1b8b9a68172f");
                _resourcesInfo = new RepoItemInfo(this, "Resources", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Resources']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Resources']", 30000, null, "238b2710-3a6a-4f2e-802d-c2170d13c301");
                _supportInfo = new RepoItemInfo(this, "Support", ".//div[#'menu_res_en']/div[@id='et-boc']/div/div/div/div/div[1]/div[1]/div/div[2]/?/?/span[@innertext='Support']", ".//div[#'menu_res_en']//span[@innertext='Support']", 30000, null, "3aedd7a4-ec4c-4626-bc54-07f5d6e1df7f");
                _functionaluitestautomationwithintelInfo = new RepoItemInfo(this, "FunctionalUITestAutomationWithIntel", ".//div[#'main-content']/article/div/div/div/div[1]/div/div[1]/div[1]/?/?/h1[@innertext>'Functional UI Test Automation']", ".//div[#'main-content']//h1[@innertext>'Functional UI Test Automation']", 30000, null, "d6afe3af-6f4d-46a7-bb93-0c3941954143");
                _ranorexgaugeb2Info = new RepoItemInfo(this, "RanorexGaugeB2", ".//div[#'main-content']/article/div/div/div/div[1]/div/div[2]//img[@title='Ranorex_Gauge_b2']", ".//div[#'main-content']//img[@title='Ranorex_Gauge_b2']", 30000, null, "bb336823-d291-49d7-b4b5-2c633805513b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b37baff4-ff5f-4f37-b0cc-131c03507304")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b37baff4-ff5f-4f37-b0cc-131c03507304")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("03c85a99-f0b2-4a45-b6c0-db9051ec0f04")]
            public virtual Ranorex.ATag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("03c85a99-f0b2-4a45-b6c0-db9051ec0f04")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }

            /// <summary>
            /// The Solutions item.
            /// </summary>
            [RepositoryItem("4174daf7-39bf-4b4d-bce4-d4b3cfd90d78")]
            public virtual Ranorex.ATag Solutions
            {
                get
                {
                    return _solutionsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Solutions item info.
            /// </summary>
            [RepositoryItemInfo("4174daf7-39bf-4b4d-bce4-d4b3cfd90d78")]
            public virtual RepoItemInfo SolutionsInfo
            {
                get
                {
                    return _solutionsInfo;
                }
            }

            /// <summary>
            /// The Ranorex item.
            /// </summary>
            [RepositoryItem("911735bc-fea3-4a07-90f6-1b8b9a68172f")]
            public virtual Ranorex.ImgTag Ranorex
            {
                get
                {
                    return _ranorexInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Ranorex item info.
            /// </summary>
            [RepositoryItemInfo("911735bc-fea3-4a07-90f6-1b8b9a68172f")]
            public virtual RepoItemInfo RanorexInfo
            {
                get
                {
                    return _ranorexInfo;
                }
            }

            /// <summary>
            /// The Resources item.
            /// </summary>
            [RepositoryItem("238b2710-3a6a-4f2e-802d-c2170d13c301")]
            public virtual Ranorex.ATag Resources
            {
                get
                {
                    return _resourcesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Resources item info.
            /// </summary>
            [RepositoryItemInfo("238b2710-3a6a-4f2e-802d-c2170d13c301")]
            public virtual RepoItemInfo ResourcesInfo
            {
                get
                {
                    return _resourcesInfo;
                }
            }

            /// <summary>
            /// The Support item.
            /// </summary>
            [RepositoryItem("3aedd7a4-ec4c-4626-bc54-07f5d6e1df7f")]
            public virtual Ranorex.SpanTag Support
            {
                get
                {
                    return _supportInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Support item info.
            /// </summary>
            [RepositoryItemInfo("3aedd7a4-ec4c-4626-bc54-07f5d6e1df7f")]
            public virtual RepoItemInfo SupportInfo
            {
                get
                {
                    return _supportInfo;
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item.
            /// </summary>
            [RepositoryItem("d6afe3af-6f4d-46a7-bb93-0c3941954143")]
            public virtual Ranorex.H1Tag FunctionalUITestAutomationWithIntel
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item info.
            /// </summary>
            [RepositoryItemInfo("d6afe3af-6f4d-46a7-bb93-0c3941954143")]
            public virtual RepoItemInfo FunctionalUITestAutomationWithIntelInfo
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo;
                }
            }

            /// <summary>
            /// The RanorexGaugeB2 item.
            /// </summary>
            [RepositoryItem("bb336823-d291-49d7-b4b5-2c633805513b")]
            public virtual Ranorex.ImgTag RanorexGaugeB2
            {
                get
                {
                    return _ranorexgaugeb2Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The RanorexGaugeB2 item info.
            /// </summary>
            [RepositoryItemInfo("bb336823-d291-49d7-b4b5-2c633805513b")]
            public virtual RepoItemInfo RanorexGaugeB2Info
            {
                get
                {
                    return _ranorexgaugeb2Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
